# Header
menu:
  主页: /
  洛谷: https://luogu.org

footer_icons:
  'Theme on GitHub':
    url: 'https://github.com/luogu-cat/Gradient'
    class: 'fab fa-github'

sidebar:
  cats:
    -
      name: "七仔"
      list:
        - 品种：英短虎斑
        - 性别：♀
        - 出生日期：2018-05-08
        - 体重：3.1kg (动态中
      more:
        - ps 现在学会跳上水槽找吃的了 T-T
        - 18.12.7 今天企图偷吃解冻的肉被抓现行

featured_image: ./img/default.jpg

google_analytics: UA-128235720-3
